baseURL: "https://blog.kunalsin9h.dev"
title: Kunal Singh
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  title: Kunal's Blog
  description: "These are my writing."
  keywords: [Blog, Portfolio]
  author: Kunal Singh
  # author: ["Me", "You"] # multiple authors
  # images: []
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "https://kunalsin9h.dev/store/images/favicon.png"
    favicon16x16: "https://kunalsin9h.dev/store/images/favicon.png"
    favicon32x32: "https://kunalsin9h.dev/store/images/favicon.png"
    apple_touch_icon: "https://kunalsin9h.dev/store/images/favicon.png"
    safari_pinned_tab: "https://kunalsin9h.dev/store/images/favicon.png"

  label:
    text: "Kunal's Blog"
    # icon: /apple-touch-icon.png
    # iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: Kunal Singh
    subtitle: "Hello I am kunal"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts

  # home-info mode
  homeInfoParams:
    Title: "Articles"
    Content: Welcome to my blog

  socialIcons:
    - name: github
      url: "https://github.com/kunalsin9h"
    - name: twitter
      url: "https://twitter.com/kunalsin9h"
    - name: linkedin
      url: "https://www.linkedin.com/in/kunalsin9h/"
    - name: email
      url: "mailto:kunal@kunalsin9h.dev"

  cover:
    hidden: true  # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/KunalSin9h/blog/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
  main:
    - identifier: archive
      name: archive
      url: /archives/
      weight: 1
    - identifier: tags
      name: tags
      url: /tags/
      weight: 2
    - identifier: search
      name: search
      url: /search/
      weight: 3
    - identifier: github
      name: github
      url: https://github.com/KunalSin9h/blog
      weight: 4

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai